# .github/workflows/python-ci.yml
name: CI for Python apps

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
                     
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Format code
        run: |
          pip install black
          black .
      
      - name: Run linting
        run: |
          pip install flake8
          flake8 .

      - name: Run tests with coverage
        run: |
          pip install coverage pytest-cov
          pytest --cov=your_project

      - name: Debugging step
        run: echo "All steps completed successfully!"
